FROM node:14

RUN mkdir -p /usr/src/node-api
WORKDIR /usr/src/node-api
COPY . .

ENV NODE_ENV=production
ENV NODE_APP_CORS_URL=http://localhost:3000

RUN npm install --production && npm run build

EXPOSE 3000

CMD [ "npm", "start" ]
